spring:
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/test
    username: root
    password: password
  flyway:
    url: jdbc:mariadb://localhost:3306/test
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true

mosquitto:
  uri: tcp://localhost:8883
  username: giangi
  password: password
  truststorePath: testTruststore
  truststorePassword: testTruststorePassword