spring:
  r2dbc:
    url: r2dbc:mariadb://localhost:3306
    username: root
    password: password
    name: test

mosquitto:
  uri: tcp://localhost:8883
  username: giangi
  password: password
  truststorePath: testTruststore
  truststorePassword: testTruststorePassword