version: '3.9'

services:
  traefik:
    container_name: traefik
    image: "traefik:v2.6.0"
    command:
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --api
    ports:
      - "80:80"
    networks:
      - traefik-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme:/acme"
    labels:
    # DASHBOARD
      - "traefik.http.routers.traefik.rule=Host(`traefik.domos.local`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=admin"
      - "traefik.http.middlewares.admin.basicauth.users=admin:$$apr1$$Dqo7TC2B$$23bAWltXXzx01XUbq2BU50"
    # GLOBAL REDIRECT TO HTTPS
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"

networks:
 traefik-proxy:
   name: traefik-proxy
