version: '3.9'

services:
  domobot:
    image: giangi/domobot-server:latest
    container_name: domobot
    networks:
      - domos-network
    depends_on:
      - loki
    ports:
      - "8080:8080"
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224

  grafana:
    image: grafana/grafana:9.1.2
    container_name: grafana
    depends_on:
      - loki
    ports:
      - "3000:3000"
    networks:
      - domos-network
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - "./observability/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml"
      - "./observability/grafana/dashboards:/etc/grafana/provisioning/dashboards"
      - "./observability/grafana/grafana.ini:/etc/grafana/grafana.ini"
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224

  loki:
    image: grafana/loki:2.6.1
    container_name: loki
    depends_on:
      - fluent-bit
    ports:
      - "3100:3100"
    networks:
      - domos-network
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:2.6.1-amd64
    container_name: fluent-bit
    ports:
      - "24224:24224"
    networks:
      - domos-network
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - "./observability/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf"

  mosquitto:
    #user: giangi
    #password: password
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    depends_on:
      - loki
    user: 1000:999
    volumes:
      - "./mosquitto/config:/mosquitto/config"
      - "./certs/domos.local.crt:/mosquitto/certs/cert.crt:ro"
      - "./certs/domos.local.key:/mosquitto/certs/cert.key:ro"
      - "./certs/root.crt:/mosquitto/ca_certificates/root.crt:ro"
    restart: always
    ports:
      - "8883:8883"
      - "8884:8884"
    networks:
      - domos-network
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224

  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    depends_on:
      - domobot
      - grafana
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./nginx/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro"
      - "./certs/bundle.crt:/etc/ssl/certs/cert.crt:ro"
      - "./certs/domos.local.key:/etc/ssl/private/cert.key:ro"
    networks:
      - domos-network
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224

networks:
  domos-network:
    name: domos-network
    external: true