version: '3.9'

services:
  domobot:
    image: giangi/domobot-server:latest
    container_name: domobot
    networks:
      - domos-network
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.domobot.entrypoints=web"
      - "traefik.http.routers.domobot.rule=PathPrefix(`/web{regex:$$|/.*}`)"
      - "traefik.http.routers.domobot.middlewares=domobot-stripprefix"
      - "traefik.http.middlewares.domobot-stripprefix.stripprefix.prefixes=/web"
      - "traefik.http.services.domobot.loadbalancer.server.port=3000"
    depends_on:
      - loki
      - traefik
    ports:
      - "8080:8080"

  grafana:
    image: grafana/grafana:9.1.2
    container_name: grafana
    depends_on:
      - loki
      - traefik
    ports:
      - "3000:3000"
    networks:
      - domos-network
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.routers.grafana.rule=PathPrefix(`/grafana{regex:$$|/.*}`)"
      - "traefik.http.routers.grafana.middlewares=grafana-stripprefix"
      - "traefik.http.middlewares.grafana-stripprefix.stripprefix.prefixes=/grafana"
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./observability/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./observability/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./observability/grafana/grafana.ini:/etc/grafana/grafana.ini

  loki:
    image: grafana/loki:2.6.1
    container_name: loki
    depends_on:
      - fluent-bit
    ports:
      - "3100:3100"
    networks:
      - domos-network

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:2.6.1-amd64
    container_name: fluent-bit
    ports:
      - "24224:24224"
    networks:
      - domos-network
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./observability/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

  mosquitto:
    #user: giangi
    #password: password
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    depends_on:
      - loki
    user: 1000:999
    volumes:
      - "./mosquitto/config:/mosquitto/config"
      - "./mosquitto/data/:/mosquitto/data"
      - "./mosquitto/certs:/mosquitto/certs:ro"
      - "./mosquitto/ca_certificates:/mosquitto/ca_certificates:ro"
    restart: always
    ports:
      - "8883:8883"
      - "8884:8884"
    networks:
      - domos-network
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224

  traefik:
    container_name: traefik
    image: "traefik:v2.6.0"
    command:
      - "--accesslog=true"
      - "--log=true"
      - "--log.level=info"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik-proxy
    extra_hosts:
      - host.docker.internal:172.17.0.1
    volumes:
      - "/run/docker.sock:/var/run/docker.sock:ro"

networks:
  domos-network:
    name: domos-network
    external: true
  traefik-proxy:
    name: traefik-proxy
    external: true