version: '3.9'

services:
  domos:
    image: giangi/domobot-server:latest
    container_name: domos
    networks:
      - domos-network
      - traefik-proxy
    labels:
      - traefik.http.routers.domobot.rule=Host(`domos.local`)
      - traefik.http.routers.domobot.tls=true
      - traefik.http.routers.domobot.tls.certresolver=le
      - traefik.http.services.domobot.loadbalancer.server.port=8080
      - traefik.docker.network=traefik-proxy

    depends_on:
      - loki
    ports:
      - "8080:8080"

  grafana:
    image: grafana/grafana:9.1.2
    container_name: grafana
    depends_on:
      - loki
    ports:
      - "3000:3000"
    networks:
      - domos-network
      - traefik-proxy
    labels:
      - traefik.http.routers.grafana.rule=Host(`grafana.domos.local`)
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=le
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.docker.network=traefik-proxy
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./observability/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./observability/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./observability/grafana/grafana.ini:/etc/grafana/grafana.ini

  loki:
    image: grafana/loki:2.6.1
    container_name: loki
    depends_on:
      - fluent-bit
    ports:
      - "3100:3100"
    networks:
      - domos-network

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:2.6.1-amd64
    container_name: fluent-bit
    ports:
      - "24224:24224"
    networks:
      - domos-network
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./observability/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

  mosquitto:
    #user: giangi
    #password: password
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    depends_on:
      - loki
    user: 1000:999
    volumes:
      - "./mosquitto/config:/mosquitto/config"
      - "./mosquitto/data/:/mosquitto/data"
      - "./mosquitto/certs:/mosquitto/certs:ro"
      - "./mosquitto/ca_certificates:/mosquitto/ca_certificates:ro"
    restart: always
    ports:
      - "8883:8883"
      - "8884:8884"
    networks:
      - domos-network
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224

networks:
  domos-network:
    name: domos-network
    external: true
  traefik-proxy:
    name: traefik-proxy
    external: true