version: '3.9'

services:
  domobot:
    image: giangi/domobot-server:latest
    container_name: domobot
    networks:
      - domos-network
      - traefik-proxy
    labels:
      - "traefik.http.routers.domobot.rule=Path(`/`)"
      - "traefik.http.services.domobot.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik-proxy"
    depends_on:
      - loki
      - traefik
    ports:
      - "8080:8080"

  grafana:
    image: grafana/grafana:9.1.2
    container_name: grafana
    depends_on:
      - loki
      - traefik
    ports:
      - "3000:3000"
    networks:
      - domos-network
      - traefik-proxy
    labels:
      - "traefik.http.routers.grafana.rule=Path(`/grafana`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik-proxy"
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./observability/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./observability/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./observability/grafana/grafana.ini:/etc/grafana/grafana.ini

  loki:
    image: grafana/loki:2.6.1
    container_name: loki
    depends_on:
      - fluent-bit
    ports:
      - "3100:3100"
    networks:
      - domos-network

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:2.6.1-amd64
    container_name: fluent-bit
    ports:
      - "24224:24224"
    networks:
      - domos-network
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./observability/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

  mosquitto:
    #user: giangi
    #password: password
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    depends_on:
      - loki
    user: 1000:999
    volumes:
      - "./mosquitto/config:/mosquitto/config"
      - "./mosquitto/data/:/mosquitto/data"
      - "./mosquitto/certs:/mosquitto/certs:ro"
      - "./mosquitto/ca_certificates:/mosquitto/ca_certificates:ro"
    restart: always
    ports:
      - "8883:8883"
      - "8884:8884"
    networks:
      - domos-network
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224

  traefik:
    container_name: traefik
    image: "traefik:v2.6.0"
    command:
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --api
    ports:
      - "80:80"
    networks:
      - traefik-proxy
    volumes:
      - "/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      # DASHBOARD
      - "traefik.http.routers.traefik.rule=Host(`domos.local`)"
      - "traefik.http.routers.grafana.rule=Path(`/traefik`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=admin"
      - "traefik.http.middlewares.admin.basicauth.users=admin:$$apr1$$Dqo7TC2B$$23bAWltXXzx01XUbq2BU50"
      # GLOBAL REDIRECT TO HTTPS
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"

networks:
  domos-network:
    name: domos-network
    external: true
  traefik-proxy:
    name: traefik-proxy
    external: true