version: '3.9'

services:
  grafana:
    image: grafana/grafana:9.1.2
    container_name: grafana
    depends_on:
      - loki
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./observability/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./observability/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./observability/grafana/grafana.ini:/etc/grafana/grafana.ini

  loki:
    image: grafana/loki:2.6.1
    container_name: loki
    depends_on:
      - fluent-bit
    ports:
      - "3100:3100"

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:2.6.1-amd64
    container_name: fluent-bit
    ports:
      - "24224:24224"
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./observability/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

  mosquitto:
    #user: giangi
    #password: password
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    depends_on:
      - loki
    user: 1000:999
    volumes:
      - "./mosquitto/config:/mosquitto/config"
      - "./mosquitto/data/:/mosquitto/data"
      - "./mosquitto/certs:/mosquitto/certs:ro"
      - "./mosquitto/ca_certificates:/mosquitto/ca_certificates:ro"
    restart: always
    ports:
      - "8883:8883"
      - "8884:8884"
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224